# This workflow will upload a Python Package to PyPI.

name: PyPI

on:
  push:
    tags:
    - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      # Could also use: poetry build
      run: python -m build

    - name: Check distribution's long description rendering on PyPI
      run: twine check dist/*

    - name: Publish package to PyPI
      if: github.repository == 'KAUTH/auto-click-auto'
      uses: pypa/gh-action-pypi-publish@release/v1

