# This workflow will install Python dependencies, run tests for a series of Python versions.

name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install pip, tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run Python tests
      run: make all-tests
